# Site settings
author: Dara Paoletti
title: 
header-img: img/home-bg.png
email: dara.paoletti@flatironschool.com
copyright_name: Dara Paoletti
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  darapaoletti

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
